# Generated by Django 3.1.5 on 2021-01-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopSelfService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(choices=[('goods', 'Goods/Product'), ('service', 'Services'), ('fast food ', 'Fast Food')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefered not to say', 'Prefered not to say')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('out for delivery', 'out for delivery'), ('cancled', 'Cancled')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
    ]
