# Generated by Django 3.1.5 on 2021-01-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
