# Generated by Django 3.1.5 on 2021-01-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
