# Generated by Django 3.1.5 on 2021-01-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_auto_20210113_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='PlacedOrder',
        ),
    ]
